### ISSUE TITLE
java.lang.NullPointerException is thrown when opening the app for the first time

### ISSUE THREAD

**Issue by rowest** [Kumulos/KumulosSdkAndroid#66]
java.lang.NullPointerException is thrown when opening the app for the first time.
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.concurrent.Future java.util.concurrent.ExecutorService.submit(java.lang.Runnable)' on a null object reference
       at com.kumulos.android.Kumulos.trackEvent(Kumulos.java:384)
       at com.kumulos.android.Kumulos.pushTokenStore(Kumulos.java:608)
       at com.kumulos.android.FirebaseMessagingService.onNewToken(FirebaseMessagingService.java:20)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(FirebaseMessagingService.java:5)
       at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(EnhancedIntentService.java:1)
       at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run(EnhancedIntentService.java:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(zza.java:2)
       at java.lang.Thread.run(Thread.java:923)
```

Reproduces on Android 11 and Android 9 with kumulos SDK v.12.0.0

Here is the code that leads to crash (Kumulos.java:384):
```
 /** package */ static void trackEvent(@NonNull final Context context, @NonNull final String eventType, @Nullable final JSONObject properties, final long timestamp, boolean immediateFlush) {
        if (TextUtils.isEmpty(eventType)) {
            throw new IllegalArgumentException("Kumulos.trackEvent expects a non-empty event type");
        }

        Runnable trackingTask = new AnalyticsContract.TrackEventRunnable(context, eventType, timestamp, properties, immediateFlush);
        executorService.submit(trackingTask);
    }
```
On the second and subsequent app launches the SDK works as expected

**Comment by rowest** [comment]
I've also noticed the same error when the app is trying to call in the background
```
    @Override
    protected void onPushReceived(Context context, PushMessage pushMessage) {
        Logger.debug(KumulosPushBroadcastReceiver.class, "Push received: " + pushMessage.getTitle() +
                "\n " + pushMessage.getMessage());
        sendPush(context, pushMessage);
        super.onPushReceived(context, pushMessage); // crash here
    }
```
While the app is in foreground it works fine

**Comment by cgwyllie** [comment]
Hi @rowest,

This sounds like the SDK has not been initialised in the expected place (an Application subclass onCreate method).

Could you confirm steps for integration have been followed from: https://docs.kumulos.com/developer-guide/sdk-reference/android/#integration

Our support team would be happy to assist, please create a ticket by emailing support@kumulos.com if you want to discuss further.

Kind regards,
  Chris

**Comment by rowest** [comment]
@cgwyllie thanks, found the issue reason, it was totally my mistake
